export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";

export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";


export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";

